import tomllib
from pathlib import Path


def _load_pyproject():
    with open(Path("pyproject.toml"), "rb") as handle:
        return tomllib.load(handle)


def test_pyproject_declares_console_scripts():
    data = _load_pyproject()
    scripts = data["project"]["scripts"]

    assert scripts["portmap"] == "cli.main:main"
    assert scripts["portmap-orchestrator"] == "core_engine.orchestrator:main"
    assert scripts["portmap-master"] == "core_engine.master_node:main"
    assert scripts["portmap-worker"] == "core_engine.worker_node:main"
    assert scripts["portmap-dashboard"] == "cli.dashboard:main"


def test_pyproject_uses_runtime_requirements_file():
    data = _load_pyproject()

    assert data["project"]["dynamic"] == ["dependencies"]
    assert data["tool"]["setuptools"]["dynamic"]["dependencies"]["file"] == ["requirements.txt"]


def test_pyproject_includes_local_config_and_docs_data_files():
    data = _load_pyproject()
    data_files = data["tool"]["setuptools"]["data-files"]
    package_data = data["tool"]["setuptools"]["package-data"]

    assert package_data["core_engine"] == ["default_configs/*.json", "os_fingerprints.json", "service_fingerprints.json"]
    assert "saas*" in data["tool"]["setuptools"]["packages"]["find"]["include"]
    assert "share/portmap-ai/config/profiles" in data_files
    assert "config/profiles/default.json" in data_files["share/portmap-ai/config/profiles"]
    assert "config/profiles/raspberry_pi.json" in data_files["share/portmap-ai/config/profiles"]
    assert "share/portmap-ai/systemd" in data_files
    assert "deploy/systemd/portmap-ai-stack.service" in data_files["share/portmap-ai/systemd"]
    assert "deploy/systemd/portmap-ai-worker.service" in data_files["share/portmap-ai/systemd"]
    assert "share/portmap-ai/scripts" in data_files
    assert "scripts/install_systemd_user.sh" in data_files["share/portmap-ai/scripts"]
    assert "share/portmap-ai/gui/web" in data_files
    assert "gui/web/README.md" in data_files["share/portmap-ai/gui/web"]
    assert "share/portmap-ai" in data_files
    assert "CHANGELOG.md" in data_files["share/portmap-ai"]
    assert "PORTMAP_AI_CODEX_PHASE_19_40_HANDOFF.md" in data_files["share/portmap-ai"]
    assert "SECURITY.md" in data_files["share/portmap-ai"]
    assert "docs/CLI_REFERENCE.md" in data_files["share/portmap-ai/docs"]
    assert "docs/COMPLETION_ROADMAP.md" in data_files["share/portmap-ai/docs"]
    assert "docs/DEPLOYMENT.md" in data_files["share/portmap-ai/docs"]
    assert "docs/asset_inventory_intelligence.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PORTMAP_AI_FINAL_ROADMAP.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_J_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_K_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_L_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_M_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_N_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_O_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_P_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_Q_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_R_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_S_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_T_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_U_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_V_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_W_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/MILESTONE_X_INTEGRATION.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_59_64_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_65_70_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_71_76_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_77_82_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_87_92_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_93_98_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_99_104_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_105_110_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_111_116_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_117_122_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_123_128_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_129_134_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_135_140_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_141_146_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_147_152_PLAN.md" in data_files["share/portmap-ai/docs"]
    assert "docs/PHASE_HISTORY.md" in data_files["share/portmap-ai/docs"]
    assert "docs/ROADMAP.md" in data_files["share/portmap-ai/docs"]
    assert "docs/SECURITY_MODEL.md" in data_files["share/portmap-ai/docs"]
    assert "docs/alerting_siem_integrations.md" in data_files["share/portmap-ai/docs"]
    assert "docs/quick_start.md" in data_files["share/portmap-ai/docs"]
    assert "docs/architecture.md" in data_files["share/portmap-ai/docs"]
    assert "docs/adaptive_remediation_logic.md" in data_files["share/portmap-ai/docs"]
    assert "docs/adaptive_risk_weighting.md" in data_files["share/portmap-ai/docs"]
    assert "docs/ai_behavioral_learning.md" in data_files["share/portmap-ai/docs"]
    assert "docs/ai_layer.md" in data_files["share/portmap-ai/docs"]
    assert "docs/ai_payload_classification.md" in data_files["share/portmap-ai/docs"]
    assert "docs/ai_recommendation_engine.md" in data_files["share/portmap-ai/docs"]
    assert "docs/backup_restore_planning.md" in data_files["share/portmap-ai/docs"]
    assert "docs/autonomous_enforcement_modes.md" in data_files["share/portmap-ai/docs"]
    assert "docs/bidirectional_flow_reconstruction.md" in data_files["share/portmap-ai/docs"]
    assert "docs/behavior_correlation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/behavioral_drift_detection.md" in data_files["share/portmap-ai/docs"]
    assert "docs/behavioral_intelligence_operator_summary.md" in data_files["share/portmap-ai/docs"]
    assert "docs/baseline_aging_decay.md" in data_files["share/portmap-ai/docs"]
    assert "docs/coordinated_export_bundles.md" in data_files["share/portmap-ai/docs"]
    assert "docs/cross_node_relationship_mapping.md" in data_files["share/portmap-ai/docs"]
    assert "docs/cve_intelligence.md" in data_files["share/portmap-ai/docs"]
    assert "docs/cross_platform_firewall_provider_readiness.md" in data_files["share/portmap-ai/docs"]
    assert "docs/cross_platform_filesystem_export_safety.md" in data_files["share/portmap-ai/docs"]
    assert "docs/cross_platform_packet_capture_readiness.md" in data_files["share/portmap-ai/docs"]
    assert "docs/cross_platform_runtime_detection.md" in data_files["share/portmap-ai/docs"]
    assert "docs/cross_platform_validation_summary.md" in data_files["share/portmap-ai/docs"]
    assert "docs/cluster_runtime_health.md" in data_files["share/portmap-ai/docs"]
    assert "docs/dashboard_data_providers.md" in data_files["share/portmap-ai/docs"]
    assert "docs/dashboard_foundation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/deep_packet_inspection.md" in data_files["share/portmap-ai/docs"]
    assert "docs/deployment_manifest_generation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/deployment_operator_summary.md" in data_files["share/portmap-ai/docs"]
    assert "docs/diagnostic_relay_simulator.md" in data_files["share/portmap-ai/docs"]
    assert "docs/dynamic_topology_correlation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/dynamic_application_attribution.md" in data_files["share/portmap-ai/docs"]
    assert "docs/deployment_options.md" in data_files["share/portmap-ai/docs"]
    assert "docs/distributed_cluster_scanning.md" in data_files["share/portmap-ai/docs"]
    assert "docs/distributed_event_propagation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/distributed_node_state_sync.md" in data_files["share/portmap-ai/docs"]
    assert "docs/distributed_review_queue.md" in data_files["share/portmap-ai/docs"]
    assert "docs/distributed_visibility_aggregation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/docker_deployment.md" in data_files["share/portmap-ai/docs"]
    assert "docs/enterprise_cloud_orchestration.md" in data_files["share/portmap-ai/docs"]
    assert "docs/dns_visibility_mode.md" in data_files["share/portmap-ai/docs"]
    assert "docs/dns_destination_behavior_learning.md" in data_files["share/portmap-ai/docs"]
    assert "docs/encrypted_orchestration_transport.md" in data_files["share/portmap-ai/docs"]
    assert "docs/enterprise_security.md" in data_files["share/portmap-ai/docs"]
    assert "docs/federated_topology_aggregation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/federation_dashboard_api_readiness.md" in data_files["share/portmap-ai/docs"]
    assert "docs/federation_diagnostics.md" in data_files["share/portmap-ai/docs"]
    assert "docs/federation_runtime_manager.md" in data_files["share/portmap-ai/docs"]
    assert "docs/flow_telemetry_enrichment.md" in data_files["share/portmap-ai/docs"]
    assert "docs/flow_reconstruction.md" in data_files["share/portmap-ai/docs"]
    assert "docs/gateway_mode_validation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/gateway_router_log_ingestion.md" in data_files["share/portmap-ai/docs"]
    assert "docs/span_mirror_port_readiness.md" in data_files["share/portmap-ai/docs"]
    assert "docs/trusted_peer_lifecycle.md" in data_files["share/portmap-ai/docs"]
    assert "docs/runtime_exchange_scheduler.md" in data_files["share/portmap-ai/docs"]
    assert "docs/active_federation_validation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/event_pipeline.md" in data_files["share/portmap-ai/docs"]
    assert "docs/high_speed_scan_engine.md" in data_files["share/portmap-ai/docs"]
    assert "docs/historical_flow_baselines.md" in data_files["share/portmap-ai/docs"]
    assert "docs/historical_replay_windows.md" in data_files["share/portmap-ai/docs"]
    assert "docs/historical_network_timeline.md" in data_files["share/portmap-ai/docs"]
    assert "docs/historical_snapshot_persistence.md" in data_files["share/portmap-ai/docs"]
    assert "docs/ai_correlation_layer.md" in data_files["share/portmap-ai/docs"]
    assert "docs/ioc_intelligence_framework.md" in data_files["share/portmap-ai/docs"]
    assert "docs/dns_threat_analytics.md" in data_files["share/portmap-ai/docs"]
    assert "docs/threat_signature_framework.md" in data_files["share/portmap-ai/docs"]
    assert "docs/threat_scoring_expansion.md" in data_files["share/portmap-ai/docs"]
    assert "docs/threat_hunting_query_engine.md" in data_files["share/portmap-ai/docs"]
    assert "docs/interactive_topology_visualization.md" in data_files["share/portmap-ai/docs"]
    assert "docs/risk_dashboard_models.md" in data_files["share/portmap-ai/docs"]
    assert "docs/ipv6_dual_stack.md" in data_files["share/portmap-ai/docs"]
    assert "docs/logging_audit.md" in data_files["share/portmap-ai/docs"]
    assert "docs/live_cluster_state_synchronization.md" in data_files["share/portmap-ai/docs"]
    assert "docs/live_packet_ingestion.md" in data_files["share/portmap-ai/docs"]
    assert "docs/live_scan_snapshot_deduplication.md" in data_files["share/portmap-ai/docs"]
    assert "docs/local_api.md" in data_files["share/portmap-ai/docs"]
    assert "docs/local_storage.md" in data_files["share/portmap-ai/docs"]
    assert "docs/long_term_intelligence_operator_summary.md" in data_files["share/portmap-ai/docs"]
    assert "docs/long_term_topology_evolution.md" in data_files["share/portmap-ai/docs"]
    assert "docs/local_visibility_operator_tooling.md" in data_files["share/portmap-ai/docs"]
    assert "docs/macos_socket_collection_validation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/milestone_v_live_runtime_integration.md" in data_files["share/portmap-ai/docs"]
    assert "docs/metadata_stream_parser.md" in data_files["share/portmap-ai/docs"]
    assert "docs/multi_node_fleet_visibility.md" in data_files["share/portmap-ai/docs"]
    assert "docs/node_coordination.md" in data_files["share/portmap-ai/docs"]
    assert "docs/network_control_layer.md" in data_files["share/portmap-ai/docs"]
    assert "docs/network_topology_intelligence.md" in data_files["share/portmap-ai/docs"]
    assert "docs/network_asset_inventory.md" in data_files["share/portmap-ai/docs"]
    assert "docs/operator_review_queue_integration.md" in data_files["share/portmap-ai/docs"]
    assert "docs/operational_export_bundle.md" in data_files["share/portmap-ai/docs"]
    assert "docs/os_fingerprinting.md" in data_files["share/portmap-ai/docs"]
    assert "docs/packaging.md" in data_files["share/portmap-ai/docs"]
    assert "docs/packet_capture.md" in data_files["share/portmap-ai/docs"]
    assert "docs/packet_metadata_correlation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/passive_interface_discovery.md" in data_files["share/portmap-ai/docs"]
    assert "docs/persistent_topology_state.md" in data_files["share/portmap-ai/docs"]
    assert "docs/policy_review_engine.md" in data_files["share/portmap-ai/docs"]
    assert "docs/policy_runtime_engine.md" in data_files["share/portmap-ai/docs"]
    assert "docs/plugin_registry.md" in data_files["share/portmap-ai/docs"]
    assert "docs/platform_abstraction.md" in data_files["share/portmap-ai/docs"]
    assert "docs/protocol_metadata_extraction.md" in data_files["share/portmap-ai/docs"]
    assert "docs/quarantine_isolation_provider_readiness.md" in data_files["share/portmap-ai/docs"]
    assert "docs/production_runtime_profiles.md" in data_files["share/portmap-ai/docs"]
    assert "docs/process_service_attribution.md" in data_files["share/portmap-ai/docs"]
    assert "docs/service_behavior_fingerprints.md" in data_files["share/portmap-ai/docs"]
    assert "docs/protocol_dissectors.md" in data_files["share/portmap-ai/docs"]
    assert "docs/raspberry_pi_deployment.md" in data_files["share/portmap-ai/docs"]
    assert "docs/real_device_validation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/realtime_telemetry_dashboard.md" in data_files["share/portmap-ai/docs"]
    assert "docs/rbac_operator_permissions.md" in data_files["share/portmap-ai/docs"]
    assert "docs/remote_operator_visibility_prep.md" in data_files["share/portmap-ai/docs"]
    assert "docs/release_candidate.md" in data_files["share/portmap-ai/docs"]
    assert "docs/remediation_safety.md" in data_files["share/portmap-ai/docs"]
    assert "docs/resource_aware_historical_retention.md" in data_files["share/portmap-ai/docs"]
    assert "docs/risk_escalation_pipelines.md" in data_files["share/portmap-ai/docs"]
    assert "docs/runtime_cli.md" in data_files["share/portmap-ai/docs"]
    assert "docs/runtime_health_monitor.md" in data_files["share/portmap-ai/docs"]
    assert "docs/runtime_pipeline.md" in data_files["share/portmap-ai/docs"]
    assert "docs/runtime_session_manager.md" in data_files["share/portmap-ai/docs"]
    assert "docs/runtime_state_recovery.md" in data_files["share/portmap-ai/docs"]
    assert "docs/runtime_scheduler.md" in data_files["share/portmap-ai/docs"]
    assert "docs/saas_architecture.md" in data_files["share/portmap-ai/docs"]
    assert "docs/safety_guardrails.md" in data_files["share/portmap-ai/docs"]
    assert "docs/scanner_risk_engine.md" in data_files["share/portmap-ai/docs"]
    assert "docs/schema_validation_engine.md" in data_files["share/portmap-ai/docs"]
    assert "docs/security_authentication.md" in data_files["share/portmap-ai/docs"]
    assert "docs/secure_config_and_secrets.md" in data_files["share/portmap-ai/docs"]
    assert "docs/secure_update_framework.md" in data_files["share/portmap-ai/docs"]
    assert "docs/service_enumeration.md" in data_files["share/portmap-ai/docs"]
    assert "docs/service_lifecycle_readiness.md" in data_files["share/portmap-ai/docs"]
    assert "docs/secure_node_identity.md" in data_files["share/portmap-ai/docs"]
    assert "docs/service_mode_readiness.md" in data_files["share/portmap-ai/docs"]
    assert "docs/service_installer_templates.md" in data_files["share/portmap-ai/docs"]
    assert "docs/signed_runtime_summary_exchange.md" in data_files["share/portmap-ai/docs"]
    assert "docs/snapshot_drift_detection.md" in data_files["share/portmap-ai/docs"]
    assert "docs/source_mode_labeling.md" in data_files["share/portmap-ai/docs"]
    assert "docs/stack_stability.md" in data_files["share/portmap-ai/docs"]
    assert "docs/tamper_detection.md" in data_files["share/portmap-ai/docs"]
    assert "docs/threat_correlation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/temporal_anomaly_windows.md" in data_files["share/portmap-ai/docs"]
    assert "docs/trusted_node_transport.md" in data_files["share/portmap-ai/docs"]
    assert "docs/tui_dashboard.md" in data_files["share/portmap-ai/docs"]
    assert "docs/topology_timeline_views.md" in data_files["share/portmap-ai/docs"]
    assert "docs/tls_intelligence.md" in data_files["share/portmap-ai/docs"]
    assert "docs/traffic_flow_reconstruction.md" in data_files["share/portmap-ai/docs"]
    assert "docs/udp_scanning.md" in data_files["share/portmap-ai/docs"]
    assert "docs/unified_configuration_profiles.md" in data_files["share/portmap-ai/docs"]
    assert "docs/upgrade_migration_readiness.md" in data_files["share/portmap-ai/docs"]
    assert "docs/visualization_operator_summary.md" in data_files["share/portmap-ai/docs"]
    assert "docs/visualization_gui_platform.md" in data_files["share/portmap-ai/docs"]
    assert "docs/vulnerability_correlation.md" in data_files["share/portmap-ai/docs"]
    assert "docs/windows_runtime_compatibility.md" in data_files["share/portmap-ai/docs"]
    assert "share/portmap-ai/docs/examples" in data_files
    assert "docs/examples/assets_sample.json" in data_files["share/portmap-ai/docs/examples"]
    assert "docs/examples/services_sample.json" in data_files["share/portmap-ai/docs/examples"]
    assert "docs/examples/flows_sample.json" in data_files["share/portmap-ai/docs/examples"]
    assert "docs/examples/policy_sample.json" in data_files["share/portmap-ai/docs/examples"]
    assert "share/portmap-ai/docs/archive" in data_files
    assert "docs/archive/PHASE_44_53_INTEGRATION_PLAN.md" in data_files["share/portmap-ai/docs/archive"]
    assert "docs/archive/PHASE_44_53_PLAN.md" in data_files["share/portmap-ai/docs/archive"]
    assert "docs/archive/PHASE_54_58_INTEGRATION_PLAN.md" in data_files["share/portmap-ai/docs/archive"]
    assert "docs/archive/PHASE_54_58_PLAN.md" in data_files["share/portmap-ai/docs/archive"]
    assert "tests/node_configs/orchestrator.json" in data_files["share/portmap-ai/node_configs"]


def test_packaged_stack_defaults_exist():
    from core_engine import stack_launcher

    assert stack_launcher.DEFAULT_ORCHESTRATOR_CFG.endswith("orchestrator.json")
    assert Path(stack_launcher.DEFAULT_ORCHESTRATOR_CFG).exists()
    assert Path(stack_launcher.DEFAULT_MASTER_CFG).exists()
    assert Path(stack_launcher.DEFAULT_WORKER_CFG).exists()


def test_local_package_script_points_users_to_runtime_setup():
    text = Path("scripts/package_local.sh").read_text()

    assert "pip install -r requirements.txt" in text
    assert "portmap setup" in text
    assert "portmap doctor" in text
    assert "Docker is optional" in text
