"""Metadata-only dynamic attribution helpers."""

from core_engine.attribution.confidence_models import (
    ATTRIBUTION_CONFIDENCE_RECORD_VERSION,
    ATTRIBUTION_SAFETY_FLAGS,
    ATTRIBUTION_STATES,
    build_confidence_breakdown,
    classify_attribution_state,
    confidence_level,
    deterministic_confidence_json,
    score_application_attribution_confidence,
)
from core_engine.attribution.probabilistic_apps import (
    APPLICATION_ATTRIBUTION_RECORD_VERSION,
    ApplicationAttributionError,
    build_application_attribution_api,
    build_application_attribution_dashboard,
    build_application_attribution_report,
    build_probable_application_attribution,
    build_probable_application_attributions,
    deterministic_application_attribution_json,
    summarize_application_attributions,
)
from core_engine.attribution.signature_learning import (
    SIGNATURE_CLASSES,
    SIGNATURE_LEARNING_RECORD_VERSION,
    SIGNATURE_SAFETY_FLAGS,
    SignatureLearningError,
    build_behavioral_signature_record,
    build_behavioral_signature_records,
    build_signature_api,
    build_signature_dashboard,
    build_signature_learning_report,
    deterministic_signature_json,
    normalize_signature_class,
    score_signature_confidence,
    summarize_behavioral_signatures,
)

__all__ = [
    "APPLICATION_ATTRIBUTION_RECORD_VERSION",
    "ATTRIBUTION_CONFIDENCE_RECORD_VERSION",
    "ATTRIBUTION_SAFETY_FLAGS",
    "ATTRIBUTION_STATES",
    "ApplicationAttributionError",
    "SIGNATURE_CLASSES",
    "SIGNATURE_LEARNING_RECORD_VERSION",
    "SIGNATURE_SAFETY_FLAGS",
    "SignatureLearningError",
    "build_application_attribution_api",
    "build_application_attribution_dashboard",
    "build_application_attribution_report",
    "build_behavioral_signature_record",
    "build_behavioral_signature_records",
    "build_confidence_breakdown",
    "build_probable_application_attribution",
    "build_probable_application_attributions",
    "build_signature_api",
    "build_signature_dashboard",
    "build_signature_learning_report",
    "classify_attribution_state",
    "confidence_level",
    "deterministic_application_attribution_json",
    "deterministic_confidence_json",
    "deterministic_signature_json",
    "normalize_signature_class",
    "score_application_attribution_confidence",
    "score_signature_confidence",
    "summarize_application_attributions",
    "summarize_behavioral_signatures",
]
